name: 'Deployment'

on:
  push:
    branches:
      - prod

jobs:
  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login to registry
      # A MODIFIER
        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login rg.fr-par.scw.cloud/babyteacher-regitstry -u nologin --password-stdin
      - name: Build the Docker image for the frontend
        run: docker build . --tag rg.fr-par.scw.cloud/tayarim-registry/frontend:$GITHUB_SHA
      - name: Tag the image
        run: docker tag rg.fr-par.scw.cloud/tayarim-registry/frontend:$GITHUB_SHA rg.fr-par.scw.cloud/tayarim-registry/frontend:latest
      - name: Push the image to private registry
        run: docker push rg.fr-par.scw.cloud/tayarim-registry/frontend:$GITHUB_SHA
      - name: Push the image with latest tag
        run: docker push rg.fr-par.scw.cloud/tayarim-registry/frontend:latest

  trigger_workflow:
    runs-on: ubuntu-latest
    needs:
      - build-frontend-image
    steps:
      - name: Trigger terraform workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with: 
          owner: QuentinCoqueran
          repo: iac-tayarim
          github_token: ${{ secrets.ACTIONS_KEY }}
          workflow_file_name: terraform_deploy.yml
          ref: main
          wait_interval: 30
          propagate_failure: true
          wait_workflow: true
          client_payload: '{"front":"${{ github.sha }}"}'
