name: 'Deployment'

on:
  push:
    branches:
      - prod
      - master

jobs:
  deploy-frontend-image:
    runs-on: ubuntu-latest
    steps:

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: gcr.io/tayarim-project/tayarim_front:${{ github.sha }}

  trigger_workflow:
    runs-on: ubuntu-latest
    needs:
      - deploy-frontend-image
    steps:
      - name: Trigger terraform workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ESGI-project-s-teams
          repo: iac-tayarim
          github_token: ${{ secrets.ACTIONS_KEY }}
          workflow_file_name: terraform_deploy.yml
          ref: main
          wait_interval: 30
          propagate_failure: true
          wait_workflow: true
          client_payload: '{"front":"${{ github.sha }}"}'
